# Generated by Django 4.1.1 on 2022-09-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_ingredient_unique_recipe_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
